### ISSUE TITLE
Destroy bedrock with giant drill bit

### ISSUE THREAD

**Issue by MCDKlong** [Esteemed-Innovation/Flaxbeards-Steam-Power#534] opened 2022-01-03 01:56 UTC
#描述n#基本信息n*我的世界版本：n*我的世界版：n*受人尊敬的创新版本：n##崩溃报告n‘nCRASH这里的报告n`’
Destroy bedrock with giant drill bit

hello May 21, 2016 FSP-1.7.10-0.29.3 Is it intentional that it can dig bedrock even with large drill bit?（The method is to place stones above bedrock.）

**Comment by xbony2** [comment] 2022-01-03 02:44
LMAO nice. It probably isn't. Unfortunately this mod is not really supported anymore.

**Comment by MCDKlong** [comment] 2022-01-03 03:19
> 伊毛很好。不幸的是，这种模式已经不受支持了。

Even if it's not a problem, it's cool.The idea of using anti-aircraft guns for transportationIt's excellent.Thank you for your moduleIt adds endless fun to my game.（Sorry, my English is not good.The literal meaning of the translation may be wrong. ）

**Comment by elifoster** [comment] 2023-11-08 18:38
Duplicate of #474. Closed by e4d21ba064ae095e0aa8a94e02c7762d1e33bd35

**Closed as completed** 2023-11-08 18:38 UTC
Labels: Type: Bug, Status: Duplicate, Priority: High, Content: Tools, Legacy version
