### ISSUE TITLE
NPE when using engineering table and trying to put armor piece in

### ISSUE THREAD

**Issue by plazia** [Esteemed-Innovation/Flaxbeards-Steam-Power#300] opened 2015-08-13 00:42 UTC
Null Pointer Exception - client crash when loading up the Engineering table GUI. I try to select a piece of armor to modify and crash to desktop/launcher

Crash report here http://pastebin.com/cKsNv4ny

**Comment by elifoster** [comment] 2015-08-13 19:58
Duplicate of #297. Fixed in next version.

**Closed by elifoster** 2015-08-13 19:58 UTC
