### ISSUE TITLE
Strange bug w/ the Esteemed Innovation book

### ISSUE THREAD

**Issue by LeFrenjmun** [Esteemed-Innovation/Flaxbeards-Steam-Power#287] opened 2015-07-01 19:04 UTC
When I shift click something with the journal it pastes the entry over the journals menu.
![fspbug](https://cloud.githubusercontent.com/assets/13139013/8462483/3bf02136-2002-11e5-81fc-1aa6fe730c86.png)

**Comment by elifoster** [comment] 2015-07-01 19:23
Can we have some more details? Version? Client/server? Cauldron? Etc.

**Comment by LeFrenjmun** [comment] 2015-07-01 20:12
I'm using ATLauncher with MC 1.7.10. FSP version 0.28.7 and it's client-side.

**Comment by elifoster** [comment] 2015-07-30 23:46
Wait, are you using Optifine?

**Comment by LeFrenjmun** [comment] 2015-07-30 23:53
Nope. No shaders either.

**Comment by elifoster** [comment] 2015-07-30 23:59
Huh. I'll have to look into this when I can get my dev environment working. Maybe it'll be fixed by 0.28.9, idk.

**Comment by LeFrenjmun** [comment] 2015-07-31 00:01
Ok, thanks :)

**Comment by elifoster** [comment] 2015-08-05 23:50
I'm unable to duplicate this... @xbony @Strikingwolf can either of you guys duplicate it?

**Comment by LeFrenjmun** [comment] 2015-08-06 00:44
I have fastcraft on this modpack, maybe that causes it. I'll check.

**Comment by LeFrenjmun** [comment] 2015-08-06 01:09
Not the case but I found that if i close the book to it's front cover, shift clicking works properly. If I shift click something after the book has been opened, the bug occurs.

![2015-08-05_20 58 00](https://cloud.githubusercontent.com/assets/13139013/9101483/83111b5a-3bb5-11e5-8d83-d612ec0c48a4.png)
![2015-08-05_20 58 19](https://cloud.githubusercontent.com/assets/13139013/9101484/83161ab0-3bb5-11e5-93e8-786c727c3d09.png)
![2015-08-05_20 58 34](https://cloud.githubusercontent.com/assets/13139013/9101485/831a722c-3bb5-11e5-9eb1-aa820b44aa62.png)
![2015-08-05_21 03 07](https://cloud.githubusercontent.com/assets/13139013/9101486/831ea36a-3bb5-11e5-9d17-124f56da833c.png)

**Comment by Adaptivity** [comment] 2015-08-06 08:40
What minimap mod are you using? Mapwriter? Try without it. There *similar* issue exist in Tinkers Construct books (and it was caused by mapwriter).

**Comment by LeFrenjmun** [comment] 2015-08-06 15:11
I use VoxelMap, I removed it but nothing changed. I'll try removing different mods to see whats causing it.

**Comment by LeFrenjmun** [comment] 2015-08-06 15:57
The book says to control click but by default its shift click to view a blocks info. Is that just a typo?
![2015-08-06_11 35 27](https://cloud.githubusercontent.com/assets/13139013/9116367/0f6c07d2-3c32-11e5-96ef-3fd91569f225.png)

**Comment by elifoster** [comment] 2015-08-06 20:20
No... Last time I checked that feature worked. Try it in survival mode.

**Comment by LeFrenjmun** [comment] 2015-08-06 22:33
Oh I got mixed up with the block info thing.

**Comment by elifoster** [comment] 2015-08-07 02:08
The what?

**Comment by LeFrenjmun** [comment] 2015-08-07 03:10
The feature that allows you to get info on FSP blocks by shift clicking. Is there a shorter term we could use for that, lol.

**Comment by elifoster** [comment] 2015-08-07 05:32
Info feature? I dunno. I'm still not sure what you are now trying to report, but if it's a bug that is not the weird screen duplicating thing then make a new issue please.

**Comment by LeFrenjmun** [comment] 2015-08-07 05:45
Nope, no other bug.

**Closed** 2016-04-09 05:42 UTC
Labels: book, bug, client, prio:low, ready
