### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by Nentify** [Esteemed-Innovation/Flaxbeards-Steam-Power#173] opened 2014-12-30 16:24 UTC
Version: 0.27.2
Server: Cauldron 1.1236.06.212 (Forge 1236 - Do have Cauldron for 1272 handy if it's fixed in later Forge version)

Not sure what the cause it, it just starts spamming my logs until I butcher all the animals in the world.

If you need anymore information or help finding the cause or solution, just let me know. Would be happy to help.

**Comment by Nentify** [comment] 2015-01-01 19:14
Any extra thoughts on this?

**Comment by satanicsanta** [comment] 2015-01-01 20:53
Not particularly. I'm not sure what would even be causing it because that class has not been touched since the transition of developers, so it's just odd that it would only recently start happening.

**Comment by Nentify** [comment] 2015-01-01 20:58
It's happened for a while

**Comment by devryb** [comment] 2015-04-01 04:31
Same issue here thanks for this fix,, not

**Comment by elifoster** [comment] 2015-04-01 16:45
@devryb You shouldn't be running unsupported software. There are like no mod authors that support Cauldron anymore.

**Comment by Nentify** [comment] 2015-04-01 17:20
That's not really true...

**Comment by devryb** [comment] 2015-04-01 19:43
I can point out several instances on github here where they recently have if you'd like.
You're shutting out a huge portion of the smp players otherwise. I mean we cannn live with it I guess but generally mods that cause too much trouble and don't support cauldron in the slightest eventually get removed.

**Comment by elifoster** [comment] 2015-04-01 19:56
Cauldron is buggy and no longer being developed or maintained. You shouldn't be using it. There are other options.

**Comment by devryb** [comment] 2015-04-01 19:58
You consider Match 4th being too long ago to be deemed as no longer maintained?
http://tcpr.ca/cauldron

**Comment by Nentify** [comment] 2015-04-01 20:03
Cauldron is still semi-maintained, and there are no other viable alternatives... If there is, I'd love to know where to find them.

**Comment by elifoster** [comment] 2015-04-01 20:16
Does it still happen after 0.28.6? This seems to be a similar issue to #244. If it still happens, likely cauldrons fault. If it doesn't, cauldron has nothing to do with it.

**Comment by devryb** [comment] 2015-04-01 21:16
Thanks! Hard to test this one as I don't know exactly what reproduces it yet.
Either way thanks for taking some time to look!

**Comment by elifoster** [comment] 2015-12-01 08:09
I was stupid several months ago. Entity IDs should pretty much never be used for what it's being used there. This'll be fixed once I finish all the changes coming in the new branch, ieep.

The problem is that Entity IDs change on a lot of different occasions. I'm not going to actually test it since it seems to be a Cauldron issue, but once I eliminate probably every call to getEntityId, it should be fixed.

**Comment by elifoster** [comment] 2015-12-20 00:27
This actually won't be fixed by using ieep, but I know how to fix it regardless.

**Closed** 2015-12-20 00:40 UTC
Labels: bug, crossmod, in progress, prio:med
