### ISSUE TITLE
Server crash when player shift right-clicks steam book

### ISSUE THREAD

**Issue by kwpugh** [Esteemed-Innovation/Flaxbeards-Steam-Power#370] opened 2016-02-27 15:42 UTC
Crash report: http://pastebin.com/raw/s3FkUrvq

Forge:  forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

**Comment by elifoster** [comment] 2016-02-27 16:16
Duplicate of #362.

**Closed by elifoster** 2016-02-27 16:16 UTC
