### ISSUE TITLE
NBT Tags creating unstackable items.

### ISSUE THREAD

**Issue by Glowstonesword** [Esteemed-Innovation/Flaxbeards-Steam-Power#401] opened 2016-04-26 23:40 UTC
## Description
The latest version of Flaxbeard's Steam Power is creating null data tags on the use of any items in hitting a block called 'Speed' and 'Ticks'. This prevents the item from being stacked with 'normal' versions of itself (i.e newly mined items or spawned from creative). Once placed and broken, the tags are removed until a block is again hit with the item in hand. The tags apply to an entire stack at once.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: Irrelevant (tested on latest forge and several older versions).
* Flaxbeard's Steam Power version: 0.29.1

**Comment by elifoster** [comment] 2016-04-26 23:40
Duplicate of #389 and fixed in next version. For now, just use steam tools or your hands to break stuff.

**Closed** 2016-04-26 23:41 UTC
Labels: duplicate
