### ISSUE TITLE
Exosuit shoot pose rendering bug

### ISSUE THREAD

**Issue by Mii1128** [Esteemed-Innovation/Flaxbeards-Steam-Power#305] opened 2015-08-25 21:14 UTC
How to achieve it:

1. Put on an exosuit.
2. Take a musket and charge a Shot
3. Switch slot to Cancel Shot

What happens:

Arms get stuck in the shooting pose.

**Comment by elifoster** [comment] 2015-08-25 22:08
Bug may have been fixed in @6a13037

**Comment by elifoster** [comment] 2015-08-26 00:00
This bug is still present after the fix for the other Exosuit rendering bug.

**Comment by elifoster** [comment] 2015-08-27 15:51
What I'm thinking currently is tht the bug could be fixed by checking if the player is wearing an exosuit in ItemFirearm.onPlayerStoppedUsing. If true, force a re-render.

However this may work, special-casing is not a good way to handle things,  so I will continue doing research.

**Comment by elifoster** [comment] 2015-11-25 08:03
I have come up with another potential solution: on the ArrowLooseEvent, if it is a Firearm shot (or Rocket Launcher, will need to test), force a re-render. This is sort of a workaround, which isn't very good. I really should figure out the root cause of this issue. It's not the EnumActions as those are properly set by the model.

Here's what we discussed on November 12 in IRC, as noted by my personal notes: "We manually set armor rotation for the exosuit for sitting, standing, bow aiming, etc. We may need to special-case it. Look at onPlayerStoppedUsing in ItemBow for differences"

**Comment by Flaxbeard** [comment] 2015-11-25 16:52
I know how to fix this bug - poke me in IRC, I'll be on in like 2 hours. It has to do with caching the suit and associated issues.

Unrelated, but a lot of exo parts don't render now at least in my dev environment, including the top hat.

**Comment by elifoster** [comment] 2015-11-25 17:48
I haven't noticed that. I'll test it out at some point today

**Closed** 2015-11-25 19:21 UTC
Labels: bug, exosuit, prio:low, ready
