### ISSUE TITLE
NPE with exo helmet

### ISSUE THREAD

**Issue by Sketchygio** [Esteemed-Innovation/Flaxbeards-Steam-Power#301] opened 2015-08-13 01:18 UTC
Everytime I put the exo helmet on first I get a NPE. I can put the helmet on after i put on any other part of the exo suit  but if i try to take a piece off before the helmet i get the same error                    

here is the pastebit like for the crash report:http://pastebin.com/zUs5QzBv

**Comment by elifoster** [comment] 2015-08-13 19:57
Duplicate of #297. Fixed in next version.

**Closed by elifoster** 2015-08-13 19:57 UTC
