### ISSUE TITLE
Client Crash on load

### ISSUE THREAD

**Issue by GreatOrator** [Esteemed-Innovation/Flaxbeards-Steam-Power#448] opened 2016-06-14 11:20 UTC
## Description

So this crash happens if I change any of the default options of the config.  I literally have to delete the config, let it regen and never, ever touch it.  If i make a change, the client crashes.

The only changes I try to make are gun to false, and stop generation of ore since I am letting cofh handle that.
## Base information
- Minecraft version: 1.7.10
- Minecraft Forge version: 1566
- Flaxbeard's Steam Power version: 0.29.3
## Crash report

java.lang.NullPointerException: Initializing game
    at net.minecraft.item.ItemStack.toString(ItemStack.java:371)
    at java.lang.String.valueOf(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:115)
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:30)
    at flaxbeard.steamcraft.SteamcraftRecipes.registerExoUpgrades(SteamcraftRecipes.java:590)
    at flaxbeard.steamcraft.SteamcraftRecipes.registerCraftingRecipes(SteamcraftRecipes.java:130)
    at flaxbeard.steamcraft.SteamcraftRecipes.registerRecipes(SteamcraftRecipes.java:35)
    at flaxbeard.steamcraft.Steamcraft.load(Steamcraft.java:196)

**Comment by elifoster** [comment] 2016-06-14 16:32
What happens if you leave the gun one to true, but disable ore gen?

**Comment by GreatOrator** [comment] 2016-06-14 17:17
Either of those options changed causes a crash for me, but I can test again later today after work.

FYI:  Originally I thought it was the config needing to be regenned after updating the mod until today when I realized it was happening when I made any config changes.

**Comment by elifoster** [comment] 2016-06-14 17:31
Well, the crash in the original post is because an item that is used in crafting recipes got disabled.

**Comment by GreatOrator** [comment] 2016-06-14 20:06
Really?  what other config options should I disable along with that then?  I can give it a shot (keep in mind, this was being done after having been up for 1 hour, so results may vary based on cognitive ability) but it begs the question why would it be there to disable and not have some kind of error checking to auto disable whatever related features rely on it?

**Comment by elifoster** [comment] 2016-06-14 20:13
Hm. I took a look at line 590, and it is trying to use the Brass Piston (I think. Either that or the Turbine). AFAIK that shouldn't ever get disabled... In 1.7, the config/enabling/disabling/recipe stuff is such a mess. I'd recommend just using MT to disable the recipes for the things you want to disable, and waiting for the 1.9 update which cleans up a bunch of this stuff and will prevent errors like this by design.

**Comment by GreatOrator** [comment] 2016-06-14 21:16
well I was disabling the gun and the two ores, not the piston....but I don't use minetweaker though worse case I do use crafting manager and I should be able to disable the gun there if need be

**Comment by elifoster** [comment] 2017-02-06 08:16
This has been fixed by never setting items/blocks to null, and only using those enableWhatever config options to toggle recipes.

**Closed as completed** 2017-02-06 08:16 UTC
Labels: Type: Bug, Priority: Medium
