### ISSUE TITLE
Mekanism new world crash

### ISSUE THREAD

**Issue by Tsyklop** [Esteemed-Innovation/Flaxbeards-Steam-Power#308] opened 2015-08-28 20:06 UTC
I found that this mode does not allow to create a new world and play in the old.
When creating or loading an old world throws to the main menu.
I looked in the log file and saw a error.
The log participates Mekanism without FSP everything is fine ...

Error: http://pastebin.com/qFJ3Fya3

And: https://github.com/aidancbrady/Mekanism/issues/2933

**Comment by elifoster** [comment] 2015-08-28 21:11
Duplicate of #298

**Closed by elifoster** 2015-08-28 21:11 UTC
Labels: duplicate
